export const data = [
  {
    _id: "1",
    title: "Nike Shoes 01",
    src: "https://colibri.union-space.uz:9997/content/images/products/disport/DA2778_012_101.jpg",
    description: "Sport uslubi",
    content: "nike nike star runner 3 krossovkalari (tdv)",
    price: 40,
    colors: ["grey", "#002393"],
    count: 1,
    size: ["45", "46", "50"],
  },
  {
    _id: "2",
    title: "Nike Shoes 02",
    src: "https://colibri.union-space.uz:9997/content/images/products/disport/DH3159_101_101.jpg",
    description: "Sport uslubi",
    content: "nike nike Court Legacy krossovkalari",
    price: 109,
    colors: ["white", "pink"],
    count: 1,
    size: ["42", "44", "46"],
  },
  {
    _id: "3",
    title: "Nike Shoes 03",
    src: "https://colibri.union-space.uz:9997/content/images/products/disport/DJ6039_007_101.jpg",
    description: "Sport uslubi",
    content: "nike nike flex runner 2 krossovkalari",
    price: 70,
    colors: ["black"],
    count: 1,
    size: ["41", "45"],
  },
  {
    _id: "4",
    title: "Nike Shoes 04",
    src: "https://colibri.union-space.uz:9997/content/images/products/disport/818381_001_101.jpg",
    description: "Sport uslubi",
    content: "nike nike tanjun bg krossovkalari",
    price: 105,
    colors: ["black"],
    count: 1,
    size: ["40", "44", "46"],
  },
  {
    _id: "5",
    title: "Nike Shoes 05",
    src: "https://colibri.union-space.uz:9997/content/images/products/disport/AH6789_108_101.png",
    description: "Trening",
    content: "nike w air max 270 krossovkalari",
    price: 105,
    colors: ["#C3F29B"],
    count: 1,
    size: ["38", "40"],
  },
  {
    _id: "6",
    title: "Nike Shoes 06",
    src: "https://colibri.union-space.uz:9997/content/images/products/disport/AH8050_100_101.jpg",
    description: "Trening",
    content: "nike air max 270 krossovkalari",
    price: 207,
    colors: ["white", "#BDCCD9"],
    count: 1,
    size: ["36", "45", "46"],
  },
  {
    _id: "7",
    title: "Adidas Shoes 01",
    src: "https://colibri.union-space.uz:9997/content/images/products/disport/FY7978__101.jpg",
    description: "Sport uslubi",
    content: "adidas forum past c krossovkalari",
    price: 60,
    colors: ["black", "white", "#2D4780"],
    count: 1,
    size: ["44", "46"],
  },
  {
    _id: "8",
    title: "Adidas Shoes 02",
    src: "https://colibri.union-space.uz:9997/content/images/products/disport/GY0003__101.jpg",
    description: "Sport uslubi",
    content: "adidas forumining past krossovkalari",
    price: 90,
    colors: ["black", "white", "#97FFF4"],
    count: 1,
    size: ["42", "44", "48", "50"],
  },
  {
    _id: "9",
    title: "Adidas Shoes 03",
    src: "https://colibri.union-space.uz:9997/content/images/products/disport/GY0045__101.jpg",
    description: "Sport uslubi",
    content: "adidas treziod 2 krossovkalari",
    price: 105,
    colors: ["#7C796B", "#97FFF4", "#C08261"],
    count: 1,
    size: ["38", "40", "46.2"],
  },
  {
    _id: "10",
    title: "Adidas Shoes 04",
    src: "https://colibri.union-space.uz:9997/content/images/products/disport/GZ9687__101.jpg",
    description: "Sport uslubi",
    content: "adidas sud ipak krossovkalari",
    price: 120,
    colors: ["white", "black"],
    count: 1,
    size: ["38", "40.5", "46"],
  },
  {
    _id: "11",
    title: "Adidas Shoes 05",
    src: "https://colibri.union-space.uz:9997/content/images/products/disport/HP9087__101.jpg",
    description: "Sport uslubi",
    content: "adidas forum 84 past adv krossovkalari",
    price: 80,
    colors: ["red", "crimson", "teal", "#C08261"],
    count: 1,
    size: ["38", "40", "45"],
  },
  {
    _id: "12",
    title: "Adidas Shoes 06",
    src: "https://colibri.union-space.uz:9997/content/images/products/disport/HQ4130__101.jpg",
    description: "Trening",
    content: "adidas duramo 10 krossovkalari",
    price: 105,
    colors: ["white", "black", "#DCE0EB", "#7091F5"],
    count: 1,
    size: ["37", "43", "45"],
  },
  {
    _id: "13",
    title: "Puma Shoes 01",
    src: "https://colibri.union-space.uz:9997/content/images/products/disport/371128_40_101.png",
    description: "Sport uslubi",
    content: "Puma anzarun lite krossovkalari - soya kulrang-puma qora-puma oq",
    price: 75,
    colors: ["#333"],
    count: 1,
    size: ["40", "42", "46"],
  },
  {
    _id: "14",
    title: "Puma Shoes 02",
    src: "https://colibri.union-space.uz:9997/content/images/products/disport/376170_04_101.png",
    description: "Trening",
    content:
      "Puma pwrframe tr wn's krossovkalari - puma qora-chuqur orkide-neon cit",
    price: 99,
    colors: ["white", "pink"],
    count: 1,
    size: ["38", "40", "42", "45"],
  },
  {
    _id: "15",
    title: "Puma Shoes 03",
    src: "https://colibri.union-space.uz:9997/content/images/products/disport/376164_01_101.jpg",
    description: "Sport uslubi",
    content: "Puma softride fly krossovkalari - puma qora-puma oq",
    price: 40,
    colors: ["white", "Black"],
    count: 1,
    size: ["35", "40", "44", "45"],
  },
  {
    _id: "16",
    title: "Puma Shoes 04",
    src: "https://colibri.union-space.uz:9997/content/images/products/disport/377312_02_101.png",
    description: "Trening",
    content:
      "Krossovkalar puma transport zamonaviy yaxshiroq - kechqurun osmon-parisi nig",
    price: 70,
    colors: ["#333", "#555"],
    count: 1,
    size: ["39", "40", "42", "48"],
  },
  {
    _id: "17",
    title: "Puma Shoes 05",
    src: "https://colibri.union-space.uz:9997/content/images/products/disport/383157_01_101.png",
    description: "Sport uslubi",
    content: "Puma cali dream lth wns krossovkalari - puma oq",
    price: 107,
    colors: ["white"],
    count: 1,
    size: ["37.1", "40", "43", "45"],
  },
  {
    _id: "18",
    title: "Puma Shoes 06",
    src: "https://colibri.union-space.uz:9997/content/images/products/disport/385279_02_101.png",
    description: "Sport uslubi",
    content:
      "Krossovkalar puma cassia sl - puma black-puma black-puma team gold",
    price: 80,
    colors: ["black"],
    count: 1,
    size: ["36", "41", "42", "44"],
  },
];
